apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:1n8qY/3Re5tPvV2ckcnIycLtVT7DNZLLtCqGk0z4BymSRRLQKQmRAw==,iv:+6Y/g8DZ0w8yhQUbT6mcGxiJ+9DY5Omj38rsi96Irtg=,tag:oJksSlY/f7fhdNPVm5ocDA==,type:str]
sops:
  age:
    - recipient: age1qq7yp5n0vec4ufmapynhzd3xap4c9vrkeems67jdwchjwjxwvq0qyw3nfx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUjg3V3VTVWtXaWRZSXkv
        cVgyWlVFeWJtblZ6WWk0ZmU3dVpLVFYrL0RNCkhpeEE3aWNveHNieko1WWtKRFZi
        UHk2TUlOVzZMb1kxaXAySzU0MzdZZXMKLS0tIFAweGJ6VUZtTDhqZm1xRUUxOGVM
        VEwwOWF0MUc0Vmh5RmxCN1UzRG85WVEKqHd37Zcn4qEJTGi79vkIhCue+MjPyRkx
        5REr4LnU2fsLQYLmI3RP/Mu7lsEzwprPDE9bDP+m2GQ9WT5xcFTW8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T22:21:49Z"
  mac: ENC[AES256_GCM,data:2Vsm6QE6pBU/kGiF9X+CHhLeafYGznc1opd6S8am180h22+KdtHGkPqLj+u0pDyGCZK6PNlbAGlvUfLCbKCRrpYf4FdpRL8TK8/qnmgOpQCxnhxjLqc69BGRvdCZzoikQf2DWJCQ1puh2DRNiWmSj3mtlYWblTkQzOjlOlv3JZ8=,iv:W7NZMOBS94XnRedIEK/3qf+9fCqLUm7KCl36fEj2e7A=,tag:p0MSzFKTv9PcohsMYw/zlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
