apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vm7aCEZLOt7HKB6wVA==,iv:M0ZbaUxXrWyfPPI3vASC8iVbktiI/o2XFKEfnyJOIBQ=,tag:roBHzjfTZ1inj1J/3ZIhgA==,type:str]
sops:
  age:
    - recipient: age1qq7yp5n0vec4ufmapynhzd3xap4c9vrkeems67jdwchjwjxwvq0qyw3nfx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqKzlVQ2ZyNTVMRFcvL3dI
        UUJ4NGw5dGU4cDNyb1BwZ0hJLzBTa3l3QTBJCnFJT1pxSjdoU3B3Q1hpSGZlMHJn
        RWgrWGJhNlU1T2ZBZTd1ODNGQnBSaGsKLS0tIEZrSGZkckxJTzdDOG01L2hCUEdy
        UEZ1eFYzU1lFbHhJR3NYeFpmQktVS3MKFvPp6xRRl3FqdzcoFNXxtpvMf1ExgWYj
        rykTscCnhOteJyIzHz29a/XWq1m4p0vWNZOCtZl7mqL4XfXHZGpq2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T22:21:49Z"
  mac: ENC[AES256_GCM,data:I8gANYvyh49BWfSfsrq66o1jz42SoH6qQBZDlphBYGmOU8kiCUJ8NCEeCAtID1SoK5TMFvuaEZmMZMN348a4fiBKL/7yufkUFdIYHdtG6lc0/GNE3eI4L2xY/yRPkvWrYNiAVLwNn8GnfcZbhszs8F7Iol5xigF56S82Gp9bGXE=,iv:3CCAWWUaF+VXx/7zdJWg/GAtJkZGDvK83jsJUqLH2RM=,tag:mPQyzO04wIZmzgFtolDuSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
