apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:165ZIsYwnfqNDmh2L55/IwAweni0akgu8AqiY/d/f+8=,iv:W82DaD1ilcP+U0OSoAoIFfwEWj9no3kmEAt/SOKvA2M=,tag:387O4d8ScPXr/7aAZQ0iuA==,type:str]
sops:
  age:
    - recipient: age1qq7yp5n0vec4ufmapynhzd3xap4c9vrkeems67jdwchjwjxwvq0qyw3nfx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTGR0YmZpcC8zZGFnWHdZ
        N0RlVDBBMzlCZVhHNkVLRXVLQ1BwaFExNnd3CmNqN0ttSUJzOEFGT3Y0djNFczlE
        U25CUG43U0prb2JrNmtIVWQ4WDFraDgKLS0tIGNlRWN6MzlwdFRCTmd3Y1A0c1N4
        UmhhVmdBSGFmMkFpLys2SDFCeEgzRjgKHmu2wDsZrkPS7ThOWKE1Vv8smbQE037d
        0WZRJJoskcTZxTjuK0elNlZo3YnbeEmY3tYa3umtahOHOdhb+0tCbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T22:21:49Z"
  mac: ENC[AES256_GCM,data:S7GV2Jm+Cvqb3CWUd2aP7ronzcRA4Jkgzrqwjz2IqEmAMAsr2TgLvy/kviQTyAwHjtxPmu+bxFOAwqhnOAoxTB0CqdjxmBpp9LrFHDmYVTiYlKujpUAwWTzl+SaIHeivI/CGo0ExhFSYO8Q1ZLnircib1MXd9qHDJAoKlSJZGGo=,iv:u0K7TTfA4eUfWqsnLLFG105AKgTt2Hj4esgOeOU+od0=,tag:gq6peQuB+Mp29p8DxWHSSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
