apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:89vBVDQ0XLCHiPkK6w+XXW4T9FXWMU/KAxaZsTIXjLIV0vMKIdTziaI/PObwVx6tCUNZTQeruSS0MGzY1+jA331mlhOA3kGXQb7060wVdSpbh8QevCNgBpbHKtGqiyS1aCxAKVBqkAV5/5T+W83k0dKqaCqFr4S0qPY9fTJ/c/iLw9MzpUgIo0Pa7Dx7Aw+Jqhtgx5Zomr7Qzs0HpBNUejj/KAZJcoNfa+Rzp3g6sQtsTIgZ,iv:ZVRcwoXrb1NSjHrlB1et+SbU9iNFFvF9o0Uve5ooS4k=,tag:tIY+byKsygv1Tb5X+uNI8A==,type:str]
sops:
  age:
    - recipient: age1qq7yp5n0vec4ufmapynhzd3xap4c9vrkeems67jdwchjwjxwvq0qyw3nfx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNjVyMEZMMHczUXdZYzlK
        SXZsSEg1ZUxyQkR1em90ZlNvaUFvdU5qZENVCkdvdGFjWHl2cTBIZnNORy9sa2Fh
        TTFXLzZieS9LOWUxdW4xN09pL2RrMzAKLS0tIHlVWHZ0b1MzR0dBTU9yell3RWNi
        SEhicW5PakRRZTRJbWtucEFOWFlNbncKIUsPNxlkZQr3FcAwz2Gy+TK7Dp2eCjTZ
        9iHA880b/QORRoQQ1MskOAHz+J7giot3yQFrOks+yXfJ3XJSHcXhXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T22:21:49Z"
  mac: ENC[AES256_GCM,data:XiOelxXff/ofJCXqS9qmjUhzza13K0w7VUjHdQd2e8kvREDxJ+1REb0DNrX3ME/nv4H4dSgC7OTB8RS0kzdhv2ZP/kqa3TSmu/XKWxjDzua0Q7aPNKF8M/xC+XlwVJeX2wYcGIdcTVPi27sTLnZwEYxxqFQVMFJUea9hVGXGksQ=,iv:wdakJmr0DsL+OQaAjhLuX7UsGp2WPzHZICH9P+G0Ofs=,tag:my+cFMsDZbZDxgyfnetT7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
