apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:lBTjXpJqX9VSzQ0KYcixunpUxCNAXFyFCmd/G8eHmHg63Bs6omt+rA==,iv:IRWUhjxIdl3WaLxSvrY99Ie2Ac7wqGNAXr2nV9QRxuQ=,tag:6QKfVNpEm9dz50ihHewELA==,type:str]
sops:
  age:
    - recipient: age1qq7yp5n0vec4ufmapynhzd3xap4c9vrkeems67jdwchjwjxwvq0qyw3nfx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQUxFWWVPdU50NGhud3lW
        WDdEdVUveUVtalQxL0RGWDYrbGhxNEpZRnlnCkxvT0RYNzNTaEwrZmF5Sk5hU0xk
        Qlp6bUcxSmFPSmlURlVSU2hhZk9XYm8KLS0tIEtKL3ZBWUdxbnR6Nlh0djAxNkNC
        dUVDM2RLSDB6Z3ZZSlU5WmhQUXkrMHcKDjLN4t+ogj0G2QwdtHw/l4/5MnGlpuGD
        zJvUReL9IjWQuSMzXJzCGc6U2jVqeVWIWECx/D+P5HGWzRdz/j6uzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T22:21:49Z"
  mac: ENC[AES256_GCM,data:PNF/mo2t6DJkqnFuCE3UlRnoSOqIK0xNOMCNfG8ATwo/JPCeka69rrXkOyRcuiAr4w845Uvk+PR35P3ikd6FwDfyNluOr2XS9RMcNGgBKbJVJsTRf0o6YuLlgT5Z4Pa+YwLMePdTohorwU1/xgcgkCh3L2TXyf0VJ8U1IVeC5pw=,iv:c2hRkpGgI4w9TuInnB3GR4g7E7/kW4ABzXnTBLiG6tE=,tag:AYLco1p5O+oIDePgx5Ra4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
